### ISSUE TITLE
How to close nested modal ?

### ISSUE THREAD

**Issue by arist1213** [tjsail33/ionic-modals#1]
Let's say mine app have this process,  modal1 -> modal2 -> modal3 -> modal4
now i am in modal4, how to get back to modal1?

**Comment by timcosta** [comment]
To get back to modal 1, you will have to resolve a promise that calls the close method in each modal. 

To close a modal, use `$scope.closeModal(value)`.

To chain these, use `$ionicModal.show(params...).then(function(result){console.log("do stuff here");});`. You should be able to use these promises to resolve up the path and get back to modal1.
